name: learncraft
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.0.0
  flutter_svg: ^2.0.7
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  just_audio: ^0.10.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


